# -*- coding: utf-8 -*-

import notify_kuaidi_task
import send_delivery_item_phone_message_task
import send_order_template_message_task


from order_action_handle_service import delivery_item_refunded_handle_service
from order_action_handle_service import delivery_item_ship_info_updated_handle_service
from order_action_handle_service import delivery_item_shipped_handle_service
from order_action_handle_service import order_paid_handle_service
from order_action_handle_service import order_shipped_handle_service

